set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN V5} [get_ports G1]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN T4} [get_ports N_G2A]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN V6} [get_ports N_G2B]

set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN T6} [get_ports C]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN V7} [get_ports B]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN R8} [get_ports A]

set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN U6} [get_ports N_Y[7]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN R5} [get_ports N_Y[6]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN U7} [get_ports N_Y[5]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN R6} [get_ports N_Y[4]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN R7} [get_ports N_Y[3]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN U8} [get_ports N_Y[2]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN T11} [get_ports N_Y[1]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN V12} [get_ports N_Y[0]]