set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SD_1]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN V5} [get_ports SD_1]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets RD_1]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN T4} [get_ports RD_1]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CP1]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN V6} [get_ports CP1]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN T5} [get_ports J1]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN T6} [get_ports K1]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SD_2]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN R8} [get_ports SD_2]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets RD_2]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN U9} [get_ports RD_2]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CP2]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN T9} [get_ports CP2]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN V10} [get_ports J2]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN R10} [get_ports K2]

set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN U6} [get_ports Q1]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN R5} [get_ports Q_1]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN R6} [get_ports Q2]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN R7} [get_ports Q_2]